### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by ggebbie** [ggebbie/NobleGasRelic#1]
- [ ] * 2 x 2 degree resolution
- [x] * multiple solutions (null space) of surface timeseries
- [x] * flip time-axis: surface timeseries
- [ ] fix prime meridian
- [ ] get noble gas error, SLP prior statistics
- [ ] better global projection
- [ ] errorbars plot: PyPlot or Plots?
- [ ] diagnostics using same method to get noble gas signal
